-- Additive ARAN chat persistence schema.
-- Apply manually to the ARAN research database; never run this from app startup.
-- UUID values are generated by PostgreSQL when inserts omit the id column.

BEGIN;

CREATE TABLE IF NOT EXISTS public.conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_user_id TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT 'New Chat',
    model TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL,
    role TEXT NOT NULL,
    content JSONB NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_conversation_id
        FOREIGN KEY (conversation_id)
        REFERENCES public.conversations (id)
        ON DELETE RESTRICT
);

-- Supports owner-scoped listing ordered by most recently updated, with a stable
-- UUID tie-breaker. owner_user_id is the leftmost key, so owner-only lookups are
-- also supported by this index without a redundant single-column index.
CREATE INDEX IF NOT EXISTS idx_conversations_owner_updated_at
    ON public.conversations (owner_user_id, updated_at DESC, id DESC);

-- Supports loading a conversation's messages in chronological order with a
-- stable UUID tie-breaker.
CREATE INDEX IF NOT EXISTS idx_messages_conversation_created_at
    ON public.messages (conversation_id, created_at ASC, id ASC);

COMMIT;
